site_name: My Docs

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  
theme:
  name: material
  features:
    - navigation.tabs        # top tabs (Home, Getting started, etc.)
    - navigation.sections    # sidebar sections
    - navigation.expand
    - toc.integrate          # right-side TOC
    - search.highlight
    - content.code.copy
  # custom_dir: overrides  

extra:
  version:
    provider: mike    
  social:
  - icon: fontawesome/brands/github

extra_css:
  - assets/stylesheets/custom.css